%FILENAME%
dockerfile-language-server-0.15.0-3-any.pkg.tar.zst

%NAME%
dockerfile-language-server

%BASE%
dockerfile-language-server

%VERSION%
0.15.0-3

%DESC%
Language server for Dockerfiles

%CSIZE%
5880195

%ISIZE%
66211872

%MD5SUM%
1e6b8b2cb01edc1e9b1662bb573cbcec

%SHA256SUM%
cd63edf18549d06a0627ac4643405dc57734da1b710ea648a3ce076d4d7af2a0

%PGPSIG%
iHUEABYKAB0WIQQatsJ4/0Eim890eyyN/bV1sFOMXQUCacG7zAAKCRCN/bV1sFOMXcMwAP43gedTfWY1vCalIpqeGx7mjmFAoiI8lzfpebImX2XGkQEAlWI7zOxzJz+5jcHw080l5HEKRkNjGLlCcjZ3Xfgz/w4=

%URL%
https://github.com/rcjsuen/dockerfile-language-server

%LICENSE%
MIT

%ARCH%
any

%BUILDDATE%
1774304070

%PACKAGER%
Jonathan Grotelüschen <tippfehlr@archlinux.org>

%DEPENDS%
nodejs

%MAKEDEPENDS%
npm
git

